refactor: rename experience-builder-storybook-addon to experiences-storybook-addon [ALT-395]
contentful/experience-builder pull request #386
Opened 2024-02-16 21:36 UTC by ryunsong-contentful

## Purpose
Rename experience builder sdk packages based on https://contentful.atlassian.net/wiki/spaces/PROD/pages/4480499829/Experience+Builder+package+rename+proposal

This PR in particular converts `experience-builder-storybook-addon` to `experiences-storybook-addon`

## Approach
Create feature branch called experience-release based on the development branch.
Ignored the `CHANGELOG.md` and `package-lock.json` files as those should be auto regenerated

2024-02-19 07:47 UTC, Chaoste requested changes

2024-02-19 07:47 UTC, Chaoste commented on packages/visual-editor/package.json
> +  "version": "0.0.1-alpha.25",
```suggestion
  "version": "0.0.1-alpha.1",
```
Similar as on the other packages, I suggest that we don't start a new npmjs package at `alpha.25` but rather at `alpha.1`

2024-02-20 17:05 UTC, ryunsong-contentful commented
Hey @Chaoste we will go with your suggestion of alpha.1 for now. I'm going to assume the versioning isn't a blocker like the other PR with visual editor renaming for this specific PR into the experience-release feature branch. I will make the version changes with the big PR going against development

2024-02-20 17:07 UTC, primeinteger approved these changes

2024-02-20 17:19 UTC, merged