fix: make images media type instead of text
contentful/experience-builder pull request #490
Opened 2024-03-14 23:07 UTC by ryunsong-contentful

## Purpose

## Approach

2024-03-14 23:08 UTC, ryunsong-contentful commented on packages/core/src/definitions/styles.ts
> +  Record<ContainerStyleVariableName, ComponentDefinitionVariable<'Text' | 'Media' | 'Boolean'>>
Should be reverted

2024-03-14 23:08 UTC, ryunsong-contentful commented on packages/core/src/definitions/styles.ts
> +  Record<ContainerStyleVariableName, ComponentDefinitionVariable<'Text' | 'Media' | 'Boolean'>>
All non image related definitions should not contain media

2024-03-15 01:57 UTC, elylucas requested changes
I see the background images handled in here, but the `Image` component itself will also need its src url changed to media here: https://github.com/contentful/experience-builder/blob/development/packages/components/src/components/Image/index.ts#L25

2024-03-15 01:57 UTC, elylucas commented on packages/core/src/definitions/styles.ts
> -  Record<ContainerStyleVariableName, ComponentDefinitionVariable<'Text' | 'Boolean'>>
Good catch getting all these instances of background images. I didn't think of that.

2024-03-19 21:40 UTC, closed without merging