fix: render default content values for patterns
contentful/experience-builder pull request #580
Opened 2024-04-23 14:51 UTC by SofiaMargariti

## Purpose

When rendering a pattern in the editor, as a standalone pattern, outside of an experience, we need to still render the default (placeholder) values into the canvas to assist designers when adjusting the pattern.

## Approach

This PR makes sure that when we encounter a property with type `ComponentValue` (only available for patterns) we render the default value of the component.

2024-04-24 10:06 UTC, SofiaMargariti commented on packages/visual-editor/vitest.config.ts
> +    globals: true,
[note for reviewer] allows to use `describe`, `it`, etc.. without having to import them everyime from vitest

2024-04-26 13:03 UTC, Spring3 commented
@SofiaMargariti do we want to fix that for delivery/preview as well?

![Screenshot 2024-04-26 at 15 02 52](https://github.com/contentful/experience-builder/assets/4171202/2e196027-9db9-4e8c-93b5-95afef2e2824)

2024-04-26 13:06 UTC, SofiaMargariti commented
> @SofiaMargariti do we want to fix that for delivery/preview as well?
> 
> At the moment it is fixed only for editor mode
> 
> ![Screenshot 2024-04-26 at 15 02 52](https://private-user-images.githubusercontent.com/4171202/325985836-2e196027-9db9-4e8c-93b5-95afef2e2824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY5NjQsIm5iZiI6MTcxNDEzNjY2NCwicGF0aCI6Ii80MTcxMjAyLzMyNTk4NTgzNi0yZTE5NjAyNy05ZGI5LTRlOGMtOTNiNS05NWFmZWYyZTI4MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTMwNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI1MTllZTQ4M2NlNGNmOGU2ZjQxMjhlNDgzNzYwODg5MTI4MTA1NjIwZTJiZTFiOWI4NmY3MDExNjIxYTI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j6Zbds7e23YR-FOIvme8mjYr1ugsWZl2L6Bt5l_hwnc)

🤔 I can apply the same fix.. although should we support preview/delivery for patterns?

2024-04-26 13:10 UTC, Spring3 commented
> > @SofiaMargariti do we want to fix that for delivery/preview as well?
> > At the moment it is fixed only for editor mode
> > ![Screenshot 2024-04-26 at 15 02 52](https://private-user-images.githubusercontent.com/4171202/325985836-2e196027-9db9-4e8c-93b5-95afef2e2824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzY5NjQsIm5iZiI6MTcxNDEzNjY2NCwicGF0aCI6Ii80MTcxMjAyLzMyNTk4NTgzNi0yZTE5NjAyNy05ZGI5LTRlOGMtOTNiNS05NWFmZWYyZTI4MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTMwNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI1MTllZTQ4M2NlNGNmOGU2ZjQxMjhlNDgzNzYwODg5MTI4MTA1NjIwZTJiZTFiOWI4NmY3MDExNjIxYTI3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j6Zbds7e23YR-FOIvme8mjYr1ugsWZl2L6Bt5l_hwnc)
> 
> 🤔 I can apply the same fix.. although should we support preview/delivery for patterns?

Not certain myself, but also why not? Default values have been provided but we are not rendering them. If I created an experience and used this pattern, it would render a pattern with default values (in both - editor and preview/delivery). So why not do so for the pattern itself 🤔

2024-04-26 13:13 UTC, Spring3 approved these changes
Approving cause it works in editor mode, but I think we should do the same for preview/delivery modes

2024-04-26 13:18 UTC, dimitrycf requested changes
I wonder if we should also render those values for P+D mode? (preview and delievery).

Here's a video explaining what i mean :)

https://www.loom.com/share/53b5e4520c4d4081aa5ae784e71de39f

2024-04-26 13:19 UTC, dimitrycf approved these changes
UNBLOCKING, re my and @Spring3  comments :)

2024-04-26 13:56 UTC, merged

2024-04-26 13:56 UTC, SofiaMargariti commented
I've updated the PR for preview/delivery mode as well, thanks everyone.