fix: ssr styles extraction for editable patterns
contentful/experience-builder pull request #707
Opened 2024-07-30 06:04 UTC by anwaar931

## Purpose

With Editable patterns we now have different styles for each pattern instance, which needs to be considered when detaching styles for SSR.

## Approach

As same pattern can have different styles, we have to store styles depending on pattern instance in an experience rather than pattern itself. 
We are generating unique `id` for each pattern child component, adding `id` to each child component of a pattern. Then storing style classes according to the id in pattern wrapper node. 
This way we are making sure to keep styles for each pattern instance separately.

2024-07-30 14:40 UTC, Spring3 approved these changes
Approving on my side, but I'd like to confirm with the others on our upcoming sync that they are fine with this patch for the time being

2024-07-31 06:52 UTC, Chaoste requested changes
As @Spring3 mentioned yesterday in the sync meeting, it will be hard to understand the rational for these changes at a later point. No matter how we follow up, we should document why the types are conflicting here and why we're doing that. I suggested how we could phrase comments to make it at least a bit more tangible.

2024-07-31 06:52 UTC, Chaoste commented on packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx
> +        ? // @ts-expect-error -- bla
I know it's always the same reason but I would really avoid leaving a comment like "bla" in the code.
]
```suggestion
      // @ts-expect-error -- node receives a random ID in ssrStyles (no type support yet)
      cfSsrClassName: node.id
        ? // @ts-expect-error -- node receives a random ID in ssrStyles (no type support yet)
```

2024-07-31 06:52 UTC, Chaoste commented on packages/experience-builder-sdk/src/blocks/preview/CompositionBlock.tsx
> +      // @ts-expect-error -- bla
```suggestion
      // @ts-expect-error -- property cfSsrClassName is a map (id to class name) that is added during rendering in ssrStyles
```

2024-07-31 06:52 UTC, Chaoste commented on packages/core/src/utils/styleUtils/ssrStyles.ts
> +          // and this is where the pattern node
What is this comment supposed to express? Maybe adjust or just remove it :)

```suggestion
          // pass top-level pattern node to store instance-specific child styles for rendering
```

2024-07-31 06:52 UTC, Chaoste commented on packages/core/src/utils/styleUtils/ssrStyles.ts
> +        };
```suggestion
        // @ts-expect-error -- temporarily add node ID to pick up the className during rendering in CompositionBlock
        currentNode.id = currentNode.id ?? generateRandomId(15);
        // @ts-expect-error -- intermediately store child classNames as map of idToValuesByBreakpoint
        patternWrapper.variables.cfSsrClassName = {
          ...(patternWrapper.variables.cfSsrClassName ?? {}),
          type: 'DesignValue',
          // @ts-expect-error -- The ID property is not yet officially typed nor supported
          [currentNode.id]: {
            valuesByBreakpoint: {
              [breakpointIds[0]]: currentNodeClassNames.join(' '),
            },
          },
        };
```

2024-07-31 06:52 UTC, Chaoste commented on packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts
> +    // @ts-expect-error TODO: fix this
```suggestion
    // @ts-expect-error -- required for SSR of custom designs on pattern instances, not yet typed
```

2024-07-31 06:52 UTC, Chaoste commented on packages/experience-builder-sdk/src/core/preview/assemblyUtils.ts
> +      // @ts-expect-error TODO: fix this
```suggestion
      // @ts-expect-error -- required for SSR of custom designs on pattern instances, not yet typed
```

2024-07-31 07:48 UTC, anwaar931 commented
Hey @Chaoste, Thanks for suggestions on comments. I have already noticed to adjust these comments yesterday but was planning to update them today. 
Updated the comments. Would be great if you can take a look before your half day. 
Thanks

2024-07-31 11:11 UTC, merged